version: "3"
services:
  app:
    build:
      context: .
      dockerfile: DockerfileDeno
    privileged: true
    command: tail -f /dev/null
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/usr/src/app:cached
    tty: true
  node:
    build:
      context: .
      dockerfile: DockerfileNode
    privileged: true
    command: tail -f /dev/null
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/app:cached
    tty: true
  redis: 
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

volumes:
  redis-data: